seek_categories = [
    "Accounting", 
        "Accounts Payable",
        "Accounts Receivable",
        "Auditing",
        "Bookkeeping & Small Practice Accounting",
        "Financial Accounting & Reporting",
        "Management Accounting & Budgeting",
        "Payroll",
        "Taxation",
    "Administration & Office Support", 
        "Administrative Assistants",
        "Data Entry & Word Processing",
        "Office Management",
        "Personal & Executive Assistants",
        "Receptionists",
    "Advertising, Arts & Media", 
        "Journalism & Writing",
        "Marketing & Communications",
        "Media Strategy, Planning & Buying",
        "Performing Arts",
        "Photography",
    "Banking & Financial Services", 
        "Banking - Business",
        "Banking - Retail",
        "Financial Planning",
        "Insurance & Superannuation",
        "Investment Banking & Corp Fin",
        "Mortgage Broking",
        "Private Equity & Venture Capital",
        "Superannuation",
    "Call Centre & Customer Service", 
        "Call Centre - Inbound",
        "Call Centre - Outbound",
        "Client Services",
        "Collections",
        "Customer Service - Call Centre",
        "Customer Service - Inbound",
        "Customer Service - Outbound",
        "Customer Service - Retail",
    "CEO & General Management", 
        "CEO",
        "COO",
        "General Manager",
        "Managing Director",
        "President",
    "Community Services & Development", 
        "Aged & Disability Support",
        "Child Protection",
        "Community Development",
        "Counselling",
        "Disability Support",
        "Family Support",
        "Indigenous Services",
        "Youth Services",
    "Construction", 
        "Architecture",
        "Building",
        "Civil/Structural Engineering",
        "Construction Management",
        "Design & Drafting",
        "Estimating",
        "Project Management",
        "Quantity Surveying",
    "Consulting & Strategy", 
        "Business Consulting",
        "Change Management",
        "Management Consulting",
        "Project Management",
        "Strategy",
    "Design & Architecture", 
        "Architecture",
        "Design",
        "Interior Design",
        "Landscape Architecture",
        "Urban Design",
    "Education & Training", 
        "Early Childhood",
        "Primary",
        "Secondary",
        "Special Education",
        "TAFE",
        "Training & Development",
        "Vocational Education & Training",
    "Engineering", 
        "Civil/Structural Engineering",
        "Electrical/Electronic Engineering",
        "Engineering Drafting",
        "Mechanical Engineering",
        "Mining, Oil & Gas Engineering",
        "Other Engineering",
        "Project Engineering",
    "Farming, Animals & Conservation", 
        "Agriculture & Horticulture",
        "Animal & Veterinary",
        "Conservation",
        "Farming, Animals & Conservation",
    "Government & Defence", 
        "Defence",
        "Government Administration",
        "Local Government",
        "Policy",
        "Regulatory & Compliance",
        "State Government",
    "Healthcare & Medical", 
        "Dentistry",
        "Medical Administration",
        "Medical Imaging",
        "Medical Research",
        "Nursing - Aged Care",
        "Nursing - General Medical & Surgical",
        "Nursing - Midwifery",
        "Nursing - Primary, Community & Preventive",
    "Hospitality & Tourism", 
        "Chefs/Cooks",
        "Concierge",
        "Event Coordination",
        "Hotel Management",
        "Housekeeping",
        "Kitchen & Sandwich Hands",
        "Management",
        "Reception",
    "Human Resources & Recruitment", 
        "Consulting & Generalist HR",
        "HR Advisors/Consultants",
        "HR Assistants",
        "HR Coordinators",
        "HR Generalists",
        "HR Managers",
        "Recruitment - Agency",
        "Recruitment - Internal",
    "Information & Communication Technology", 
        "Analyst Programmer",
        "Business Intelligence & Data Warehousing",
        "Developer",
        "Help Desk & IT Support",
        "IT Management",
        "Network & Systems Administration",
        "Project Management",
        "Security",
    "Insurance & Superannuation", 
        "Claims",
        "Insurance Brokers",
        "Insurance - General",
        "Insurance - Life",
        "Insurance - Workers Compensation",
        "Loss Adjusting",
        "Superannuation",
    "Legal", 
        "Legal Assistants",
        "Legal Secretaries",
        "Paralegals",
        "Solicitors",
        "Support Staff",
    "Manufacturing, Transport & Logistics", 
        "Forklift Drivers",
        "Labourers",
        "Manufacturing",
        "Pickers & Packers",
        "Production",
        "Quality Assurance & Control",
        "Storepersons",
        "Transport & Logistics",
    "Marketing & Communications", 
        "Brand Management",
        "Content & Copywriting",
        "Digital Marketing",
        "Marketing Assistants",
        "Marketing Coordinators",
        "Marketing Managers",
        "Media Planning & Buying",
        "Public Relations",
    "Mining, Resources & Energy", 
        "Drillers, Blasters & Shotfirers",
        "Electrical & Instrumentation",
        "Engineering - Environmental",
        "Engineering - Geotechnical",
        "Geology",
        "Health, Safety & Environment",
        "Mining - Operations",
        "Oil & Gas - Exploration & Production",
    "Real Estate & Property", 
        "Development",
        "Leasing",
        "Property Management",
        "Real Estate Sales",
        "Valuation",
    "Retail & Consumer Products", 
        "Buying",
        "Category Management",
        "Merchandising",
        "Product Management",
        "Purchasing",
        "Retail",
        "Sales - Retail",
        "Supply Chain",
    "Sales", 
        "Account Management",
        "Business Development",
        "Direct Sales",
        "Internal Sales",
        "Management",
        "Marketing",
        "Outside Sales",
        "Sales Administration",
    "Science & Technology", 
        "Biotechnology",
        "Chemistry",
        "Data Science & Analytics",
        "Environmental Science",
        "Forensic Science",
        "Life Sciences",
        "Physics",
        "Research & Development",
    "Trades & Services", 
        "Air Conditioning & Refrigeration",
        "Automotive Trades",
        "Construction Trades",
        "Electrical Trades",
        "Engineering Trades",
           "Experience in Accounting",
    "Experience in Administration & Office Support",
    "Experience in Advertising, Arts & Media",
    "Experience in Banking & Financial Services",
    "Experience in Call Centre & Customer Service",
    "Experience in CEO & General Management",
    "Experience in Community Services & Development",
    "Experience in Construction",
    "Experience in Consulting & Strategy",
    "Experience in Design & Architecture",
    "Experience in Education & Training",
    "Experience in Engineering",
    "Experience in Farming, Animals & Conservation",
    "Experience in Government & Defence",
    "Experience in Healthcare & Medical",
    "Experience in Hospitality & Tourism",
    "Experience in Human Resources & Recruitment",
    "Experience in Information & Communication Technology",
    "Experience in Insurance & Superannuation",
    "Experience in Legal",
    "Experience in Manufacturing, Transport & Logistics",
    "Experience in Marketing & Communications",
    "Experience in Mining, Resources & Energy",
    "Experience in Real Estate & Property",
    "Experience in Retail & Consumer Products",
    "Experience in Sales",
    "Experience in Science & Technology",
    "Experience in Self Employment",
    "Experience in Sport & Recreation",
    "Experience in Trades & Services"

]
 
seek_categories_test = [
    "Accounting", 
        "Accounts Payable",
        "Accounts Receivable",
        "Auditing",
        "Bookkeeping & Small Practice Accounting",
        "Financial Accounting & Reporting",
        "Management Accounting & Budgeting",
        "Payroll",
        "Taxation",
    "Administration & Office Support", 
        "Administrative Assistants",
        "Data Entry & Word Processing",
        "Office Management",
        "Personal & Executive Assistants",
        "Receptionists",
    "Advertising, Arts & Media", 
        "Journalism & Writing",
        "Marketing & Communications",
        "Media Strategy, Planning & Buying",
        "Performing Arts",
        "Photography",
    "Banking & Financial Services", 
        "Banking - Business",
        "Banking - Retail",
        "Financial Planning",
        "Insurance & Superannuation",
        "Investment Banking & Corp Fin",
        "Mortgage Broking",
        "Private Equity & Venture Capital",
        "Superannuation",
    "Call Centre & Customer Service", 
        "Call Centre - Inbound",
        "Call Centre - Outbound",
        "Client Services",
        "Collections",
        "Customer Service - Call Centre",
        "Customer Service - Inbound",
        "Customer Service - Outbound",
        "Customer Service - Retail",
    "CEO & General Management", 
        "CEO",
        "COO",
        "General Manager",
        "Managing Director",
        "President",
    "Community Services & Development", 
        "Aged & Disability Support",
        "Child Protection",
        "Community Development",
        "Counselling",
        "Disability Support",
        "Family Support",
        "Indigenous Services",
        "Youth Services",
    "Construction", 
        "Architecture",
        "Building",
        "Civil/Structural Engineering",
        "Construction Management",
        "Design & Drafting",
        "Estimating",
        "Project Management",
        "Quantity Surveying",
    "Consulting & Strategy", 
        "Business Consulting",
        "Change Management",
        "Management Consulting",
        "Project Management",
        "Strategy",
    "Design & Architecture", 
        "Architecture",
        "Design",
        "Interior Design",
        "Landscape Architecture",
        "Urban Design",
    "Education & Training", 
        "Early Childhood",
        "Primary",
        "Secondary",
        "Special Education",
        "TAFE",
        "Training & Development",
        "Vocational Education & Training",
    "Engineering", 
        "Civil/Structural Engineering",
        "Electrical/Electronic Engineering",
        "Engineering Drafting",
        "Mechanical Engineering",
        "Mining, Oil & Gas Engineering",
        "Other Engineering",
        "Project Engineering",
    "Farming, Animals & Conservation", 
        "Agriculture & Horticulture",
        "Animal & Veterinary",
        "Conservation",
        "Farming, Animals & Conservation",
    "Government & Defence", 
        "Defence",
        "Government Administration",
        "Local Government",
        "Policy",
        "Regulatory & Compliance",
        "State Government",
    "Healthcare & Medical", 
        "Dentistry",
        "Medical Administration",
        "Medical Imaging",
        "Medical Research",
        "Nursing - Aged Care",
        "Nursing - General Medical & Surgical",
        "Nursing - Midwifery",
        "Nursing - Primary, Community & Preventive",
    "Hospitality & Tourism", 
        "Chefs/Cooks",
        "Concierge",
        "Event Coordination",
        "Hotel Management",
        "Housekeeping",
        "Kitchen & Sandwich Hands",
        "Management",
        "Reception",
    "Human Resources & Recruitment", 
        "Consulting & Generalist HR",
        "HR Advisors/Consultants",
        "HR Assistants",
        "HR Coordinators",
        "HR Generalists",
        "HR Managers",
        "Recruitment - Agency",
        "Recruitment - Internal",
    "Information & Communication Technology", 
        "Analyst Programmer",
        "Business Intelligence & Data Warehousing",
        "IT Developer",
        "Help Desk & IT Support",
        "IT Management",
        "Network & Systems Administration",
        "IT Project Management",
        "Security",
    "Insurance & Superannuation", 
        "Claims",
        "Insurance Brokers",
        "Insurance - General",
        "Insurance - Life",
        "Insurance - Workers Compensation",
        "Loss Adjusting",
        "Superannuation",
    "Legal", 
        "Legal Assistants",
        "Legal Secretaries",
        "Paralegals",
        "Solicitors",
        "Support Staff",
    "Manufacturing, Transport & Logistics", 
        "Forklift Drivers",
        "Labourers",
        "Manufacturing",
        "Pickers & Packers",
        "Production",
        "Quality Assurance & Control",
        "Storepersons",
        "Transport & Logistics",
    "Marketing & Communications", 
        "Brand Management",
        "Content & Copywriting",
        "Digital Marketing",
        "Marketing Assistants",
        "Marketing Coordinators",
        "Marketing Managers",
        "Media Planning & Buying",
        "Public Relations",
    "Mining, Resources & Energy", 
        "Drillers, Blasters & Shotfirers",
        "Electrical & Instrumentation",
        "Engineering - Environmental",
        "Engineering - Geotechnical",
        "Geology",
        "Health, Safety & Environment",
        "Mining - Operations",
        "Oil & Gas - Exploration & Production",
    "Real Estate & Property", 
        "Real Estate & Property Development",
        "Leasing",
        "Property Management",
        "Real Estate Sales",
        "Valuation",
    "Retail & Consumer Products", 
        "Buying",
        "Category Management",
        "Merchandising",
        "Product Management",
        "Purchasing",
        "Retail",
        "Sales - Retail",
        "Supply Chain",
    "Sales", 
        "Account Management",
        "Business Development",
        "Direct Sales",
        "Internal Sales",
        "Management",
        "Marketing",
        "Outside Sales",
        "Sales Administration",
    "Science & Technology", 
        "Biotechnology",
        "Chemistry",
        "Data Science & Analytics",
        "Environmental Science",
        "Forensic Science",
        "Life Sciences",
        "Physics",
        "Research & Development",
    "Trades & Services", 
        "Air Conditioning & Refrigeration",
        "Automotive Trades",
        "Construction Trades",
        "Electrical Trades",
        "Engineering Trades",
           "Experience in Accounting",]


seek_job_categories = [
    "Accounting",
    "Administration & Office Support",
    "Advertising, Arts & Media",
    "Banking & Financial Services",
    "Call Centre & Customer Service",
    "CEO & General Management",
    "Community Services & Development",
    "Construction",
    "Consulting & Strategy",
    "Design & Architecture",
    "Education & Training",
    "Engineering",
    "Farming, Animals & Conservation",
    "Government & Defence",
    "Healthcare & Medical",
    "Hospitality & Tourism",
    "Human Resources & Recruitment",
    "Information & Communication Technology",
    "Insurance & Superannuation",
    "Legal",
    "Manufacturing, Transport & Logistics",
    "Marketing & Communications",
    "Mining, Resources & Energy",
    "Real Estate & Property",
    "Retail & Consumer Products",
    "Sales",
    "Science & Technology",
    "Self Employment",
    "Sport & Recreation",
    "Trades & Services"
]

